### ISSUE TITLE
Supporting Guid & a general (de)serialization question

### ISSUE THREAD

**Issue by absolutejam** [pauldorehill/FSharp.Data.Cypher#1]
Hi 👋 

Thanks for this library, I've just started playing around with it.

I noticed that the library doesn't currently support `Guid` and wondered if/how you're handling this at the moment? 

I've looked in the source and I can see where I could add it in, but I'm not sure if there's different serialization/deserialization logic (to convert from Guid -> string and string -> Guid), or if I should be using a specific DTO that uses only Neo4j-compatible types and I should create my own translation layer from domain layer to Neo4j?

Any suggestions?

Thanks!

**Comment by human-bean-555** [comment]
Hi James,

Interesting that you found this library... it seemed that F# and neo4j is an infrequent combination. As you can probably see I've not had a chance to work on it much in the last year due to other commitments; at the time neo4j was just moving to 4.0 which was a significant change; some interesting work on quotations for F#; so there was/is a lot to consider on where to take it and how to clean it up.

As to your `Guid` question - i thought about adding it but since its not an official neo4j database type i left it out. I use a `Guid` on a lot of my database types but pass them through a `string` in database layer. Its actually a very easy add, just a few changes in the Serialize.fs file.

**Comment by absolutejam** [comment]
Not really sure why, as they're both awesome technologies! I can definitely understand, but you've done some amazing work on this so far, and a lot of the quotations stuff is still way over my head.

Thanks, I think I might try using Neo4j compatible type in my records as I'm already transforming from one form (projections from an event sourced system) to these DTOs anyway, so it makes sense. I'll give it a shot and see how it fares, then resort to serializing directly if it becomes an issue.

Just trying to get the package inline with some breaking changes in the Neo4j package. Hopefully I'll get there.

**Comment by human-bean-555** [comment]
I should have a little time to look at this in the coming weeks and I'll add in a few changes now that neo4j 4.0 is stabilized, though I see that dotnet 5 is now on the cards come November.... (I've not been using dotnet for the last year) I'll look at adding in `Guid / UUId`.

As an aside, for the interface requirements I played with making the node / relationship interface simply a marker e.g. no members; or how it is currently with requiring the `labels`. 

Did you have any thoughts on if its useful having it the way it is? 

I also tried with `SRTP` where it was only required to have a `Label` method that returned the correct type, but I think that is where I ran up against some of the limits of quotations both on the compiler and my understanding! It may now be possible with the merging of some things around witness parsing for quotations.

**Comment by absolutejam** [comment]
I seem to have gotten the necessary breaking changes sorted for Neo4j.Driver 4.1 in a branch, and all tests pass except 1. I've not looked at the `Guid` part yet as I'm still toying with the library overall, and because my domain events use single-case DUs a lot (eg. `Name of string` instead of just `string`) then I'm either going to have to settle on a translation layer or look at the (de/)serialization features.

I like the current implementation as it's simple but enforces the bare minimum, as you realistically need label(s) no matter what.

I might have a couple more questions about general usage. Would it be possible to reach out to you somewhere (even if it's in a GitHub issue), if you have the interest and time?

Regards.

**Comment by human-bean-555** [comment]
I think I did implement single case DUs in the serde... its been a while since i went over the code. Yeah no worries about reaching out - I'm based on the east coast of Australia so there maybe some time zones to consider, not sure where would be preferable: a Slack / Discord server might be a good option?

**Comment by absolutejam** [comment]
Sorry for the (super) late reply! Been away with the family then back to the grindstone.

That'd be awesome. I'm just coming around to revisiting this and I'm really interested in getting a better understanding. I'm in the functional programming & F# slack as well as a bunch of other Slacks & Discords.

I've been working on a PromQL implementation/DSL in F#, so I was wondering if I could try and expand what's available here. One thing I'm really curious about is the use of quotations, so it'd be great to have a quick chat about those.

Cheers!
